Properly escape interpolation-like strings in resolved configs
omry/omegaconf pull request #1113
Opened 2023-08-08 15:54 UTC by odelalleau

Fixes #1112
Fixes #1081

This is a draft PR for two reasons:
1. It needs tests + news fragment
2. It is built on top of #1109 that needs to be merged first

Note that this is a breaking change, but it can be argued that the previous behavior was a bug (all tests pass).

2023-08-08 22:51 UTC, Jasha10 approved these changes
Looks good to me!

2023-08-14 02:24 UTC, omry commented
I think this needs tests to show what it's actually doing and to ensure it does not break in the future.

2023-08-14 11:53 UTC, odelalleau commented
> I think this needs tests to show what it's actually doing and to ensure it does not break in the future.

Oh yes (see point 1 above)

> Also, worth considering any performance impact.

I need to think about it a bit more, but I don't believe this is an issue. Will keep it in mind though.

2023-08-15 08:16 UTC, MatteoVoges commented
Hey I noticed a breaking change with this. See full description of it here: https://github.com/omry/omegaconf/issues/1112#issuecomment-1678573449

2026-05-10 15:56 UTC, omry requested changes
Thanks for putting this together.

Closing this draft because both issues it was intended to address (#1112 and #1081) have been rejected / resolved without taking this implementation approach. This PR is therefore no longer planned for merge.

2026-05-10 15:56 UTC, closed without merging