Support YAML merge tags
omry/omegaconf pull request #507
Opened 2021-02-02 22:37 UTC by jgehring

This adds support for YAML merge tags (<< *ref) while retaining the
sanity check for duplicate keys. Note that the spec for merge keys
(https://yaml.org/type/merge.html) explicitly states that keys in the
current mapping override the ones in the merged mapping. Hence, the
check for duplicates is applied to scalar keys of the current mapping
only.

Fixes #470.

2021-02-02 23:55 UTC, omry requested changes
Very clean, thanks :)
See small request.

2021-02-02 23:55 UTC, omry commented on tests/test_serialization.py
> +        cfg = OmegaConf.load(fp.name)
no need to go through a file. you can initialize OmegaConf directly from a yaml string:

```
cfg = OmegaConf.create(content)
```

At this point, also clean up test_load_duplicate_keys_top().
I think both tests belongs in test_create().

2021-02-03 00:23 UTC, omry commented
Please add a news fragment file in the news directory.

2021-02-03 00:26 UTC, omry requested changes
see comments.
also, please add  a news fragment for the bug fix.

2021-02-03 00:26 UTC, omry commented on tests/test_create.py
> +def test_yaml_duplicate_keys() -> None:
1. do not merge the tests. two different behaviors gets two tests. (one for duplicate keys, one for merge support).
2. looks like you have two tests for duplicate keys. Can you parameterize with pytest.mark.parametereize?

2021-02-03 18:34 UTC, omry commented
Looking good.
you have some lint issues (isort).
you can run nox locally (e.g. nox -s lint-3.8).

2021-02-03 18:36 UTC, omry requested changes
1. Please fix lint issues (hints in the [contributing](https://github.com/omry/omegaconf/blob/master/CONTRIBUTING.md) doc)
2. Please add a new s fragment.  This is similar to Hydra, see [this](https://hydra.cc/docs/development/documentation#news-entries).

2021-02-03 22:20 UTC, omry requested changes
Almost.
We generate the NEWS.md from the files in the news directory using towncrier.

It's really simple, but you have to read the link I provided :)

basically, create a file:
```
news/ISSUE_ID.bugfix
```

With the content of the news entry.
```
Support merge tags in YAML files
```

The file name should be after the issue, not the pull request.
so in this case `news/470.bugfix`.

2021-02-03 22:35 UTC, jgehring commented
Haha, sorry for messing it up :)

2021-02-03 22:47 UTC, omry approved these changes
Awesome, thanks for fixing it!

2021-02-03 22:57 UTC, merged

2021-03-07 18:01 UTC, gchhablani commented
Hi @omry,

Will the next release include this feature? When is it scheduled?

2021-03-07 19:03 UTC, omry commented
This bug fix (not a feature) will be included in 2.1.
It will be released when 2.1 is ready. In the mean time you can use the 2.1 dev release. (`pip install omegaconf --pre --upgrade`) but note that it's not finalized.

2021-03-10 06:10 UTC, gchhablani commented
Hi @omry,

I installed the latest dev version. Now, interpolation doesn't work even if there is no YAML merge.

2021-03-10 06:22 UTC, omry commented
There are about 500 unit tests covering interpolation. If you think you have a big please file a new issue a minimal repro.

2021-03-10 08:06 UTC, gchhablani commented
Hi @omry,

I apologize. Interpolation works fine. I was checking it the wrong way.

Infact, interpolation with YAML merge also works:
Like this:
```
default: &default
  a: 1
  b: 2

modify1: 
  <<: *default
  c: ${default.b}
```

Output on printing:
```
{'default': {'a': 1, 'b': 2}, 'modify1': {'a': 1, 'b': 2, 'c': '${default.b}'}}
{'a': 1, 'b': 2}
1
2
{'a': 1, 'b': 2, 'c': '${default.b}'}
1
2
2
```