Additional optimization to update() without force_add
omry/omegaconf pull request #673
Opened 2021-04-08 14:37 UTC by odelalleau

This avoids invalidating the flags cache with `force_add=False`.

This gives a ~10% speed-up on the benchmark test_update_force_add that
updates the key ""a.a.a.a.a.a.a.a.a.a.a" (previous benchmark), and a
~50% speed-up on the new (and faster) benchmark that just updates "a".

This commit also fixes an issue with this benchmark, where re-using the
same config across tests was introducing dependencies between tests.

======================

This is the other optimization I had suggested in https://github.com/omry/omegaconf/pull/665#discussion_r608611363

Note: there is still an issue with this benchmark because the large dictconfig is only created once for each test, and re-used across the multiple calls to the function within `benchmark()`. As a result both the flags cache and the config itself aren't the same between the first call and subsequent calls.

I tried to play with the pedantic mode (https://pytest-benchmark.readthedocs.io/en/latest/pedantic.html) to have a proper setup always providing the same config as input, but I got very surprising timing results. I wasn't sure if there was an issue with my code, my understanding of the pedantic mode, or if these results were actually correct, so I didn't investigate further at this time.

2021-04-12 12:02 UTC, odelalleau commented
NB: I rebased and pushed a new version which is simpler (always using our own implementation of `nullcontext` instead of trying to import the one from Python first). This is because the implementation from CPython is in Python anyway (at least in 3.7), so there's no performance benefit in using it.

2021-04-14 21:35 UTC, omry requested changes
Looks good. one small request.

2021-04-14 21:47 UTC, odelalleau commented on benchmark/benchmark.py
> +
Indeed, that sounds better => done in 55baba6

2021-04-14 23:56 UTC, omry approved these changes
gogo.

2021-04-15 12:06 UTC, merged